### ISSUE TITLE
dependency on symfony/yaml 2.7.* to symfony/yaml ~2.7.*

### ISSUE THREAD

**Issue by lo3ty** [nathanmac/Parser#11]
hi there,
i want to use your package in a laravel 5.1 application. it seems to be that something that laravel uses, requires symfony ~2.8.*. Since your package requires 2.7.* and NOT ~2.7.* composer cannot import your package.

It would be awesome if you could change that :)

thanks, Leonhard

**Comment by nathanmac** [comment]
@lo3ty - v3.7 should be good to go with L5
Thanks
