### ISSUE TITLE
Documentation isn't clear.

### ISSUE THREAD

**Issue by xitude** [nathanmac/Parser#13]
Thanks for this package..
I'm trying to get Lumen to convert my default DB::all() to a XML that I can define the tree.

This is for google product services that requires a XML feed, do you know if this package can allow me to complete that task?

I've tried doing something like..
`````php
$payload = Product::findOrFail($id);

        return Parser::xml($payload);
```````

But I get Failed To Parse XML

**Comment by xitude** [comment]
I've tried doing something like..
`````php
$payload = Product::findOrFail($id);

        return Parser::xml($payload);
```````

**Comment by nathanmac** [comment]
This library is not designed to convert arrays to xmls output, it converts xml strings to php arrays.

```
Parser::xml($payload);          // XML > Array
```

```
$result = Parser::xml(
    '<xml><comments><title></title><message>hello world</message></comments><comments><title>world</title><message></message></comments></xml>'
);
```

Returns

```
array(
    "comments" => array(
        array("title" => null, "message" => "hello world"),
        array("title" => "world", "message" => null)
    )
)
```
