### ISSUE TITLE
Content-Type is not detected when the charset is added.

### ISSUE THREAD

**Issue by jvanharn** [nathanmac/Parser#14]
When you send a content type in the form of `Content-Type: application/xml; charset=utf8` it will not properly detect the content-type and parse as the default JSON instead.

The problem lies with getFormat where the content-type is directly used to check the supported formats with the content of the header. I therefore propose the Parser::getFormat method gets altered with an explode or strpos to find the first ';' character. My locally used hack is as follows:
```php
if (isset($_SERVER['CONTENT_TYPE']))
{
    $type = explode(';', $_SERVER['CONTENT_TYPE']);
    if (isset($this->supported_formats[$type[0]]))
        return $this->supported_formats[$type[0]];
}
if (isset($_SERVER['HTTP_CONTENT_TYPE']))
{
    $type = explode(';', $_SERVER['HTTP_CONTENT_TYPE']);
    if (isset($this->supported_formats[$type[0]]))
        return $this->supported_formats[$type[0]];
}
```
This can probably be done more efficiently, but as long as this problem is remedied, I'd love using your library.

**Comment by nathanmac** [comment]
@jvanharn - Thanks for point out the issue all sorted in v3.9
