### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ssi-anik** [nathanmac/Parser#24]
I've tried "composer require nathanmac/parser" command, but the command leads to error.
I've been using L5.1

![screenshot from 2016-03-17 13 40 04](https://cloud.githubusercontent.com/assets/2676602/13839520/cbfc7e54-ec45-11e5-978b-de4b561bb795.png)

**Comment by iolson** [comment]
+1

**Comment by nathanmac** [comment]
This issue was already fixed on the master branch however I forgot to push the release out.

New release `3.11` which includes a fix for this has now been pushed out.

Thanks for the report :+1:
