### ISSUE TITLE
Class 'Parser' not found

### ISSUE THREAD

**Issue by gpphong8th2** [nathanmac/Parser#25]
Hi @nathanmac,
I have install nathanmac/parser in xxamp apche, it is working, but when I deploy  my project. I have a problem Class 'Parser' not found. I am using laravel 5.1
you can give me any solution to this problem ?
Thank

**Comment by kossa** [comment]
You should add 
`Nathanmac\Utilities\Parser\ParserServiceProvider::class,` and `'Parser'    => Nathanmac\Utilities\Parser\Facades\Parser::class,` in app.php

**Comment by danhunsaker** [comment]
Also make sure you're running `composer install` on your deployed instance.  You *could* also commit/copy your `vendor/` directory to the production instance, but that's generally considered a bad approach, and kinda defeats the purpose of Composer.
