### ISSUE TITLE
Failed to parse XML

### ISSUE THREAD

**Issue by tgoettel9401** [nathanmac/Parser#34]
Hey guys,

I am using the package in a small Laravel Website I am creating for a chess club. Today I ran composer update which was updated the following packages:
- Symfony/yaml from 3.1.3 to 3.1.4
- Nathanmac/parser from 4.0 to 4.1
- Symfony/class-loader from 3.1.3 to 3.1.4
- Symfony/event-dispatcher from 3.1.3 to 3.1.4

While I was still using parser version 4.0 I was able to import and parse the XML File from [https://ssl-account.com/sbrp-ergebnisdienst.de/index.php?p1=0:ee:BK6-16&style=2]. Therefore I am simply using the following code:

`$xml = file_get_contents($url); 
$xmlArray = Parser::xml($xml);`

Unfortunately since I updated the package to 4.1 I get a ParserException in XML.php line 33: Failed To Parse XML. However it was working before and I do not understand the changes.

I would really appreciate your help guys.

Thanks!
Tobias

**Comment by danhunsaker** [comment]
Interesting result.  It shouldn't have had any issues, so I'll have to do some deep inspection of the code with your sample XML.  I may have inadvertently introduced a bug somewhere we don't yet properly test for.

**Comment by mubinov** [comment]
Hi! 

More info about this issue:
in my case error occurs here: [https://github.com/nathanmac/Parser/blob/master/src/Formats/XML.php#L68](https://github.com/nathanmac/Parser/blob/master/src/Formats/XML.php#L68)
Error message: _Illegal string offset "..."_

Thanks

**Comment by danhunsaker** [comment]
@mubinov - do you have sample XML that causes this error?

**Comment by mubinov** [comment]
` $xml = '<Info> <Reader> <num>1111</num> </Reader> </Info>';`
` \Parser::xml($xml);`


Error: _Illegal string offset 'num'_

**Comment by mubinov** [comment]
This code is works well:
```
$xml = '<Info><Reader><num>1111</num></Reader></Info>';
\Parser::xml($xml);
```

i.e. without any spaces and new lines

**Comment by danhunsaker** [comment]
Ah.  Right.  Got it.  Stupid mistake; easy fix.  I'll try to get that taken care of as soon as I have my laptop out.

**Comment by tgoettel9401** [comment]
Great guys, thank you for fixing this issue! :)

**Comment by danhunsaker** [comment]
It hasn't been merged yet, but it looks good, now.  Should be in 4.2, though this change totally fits the definition of a 4.1.1 under SemVer.

**Comment by JoshuaVR** [comment]
I think this update has created an unintended bug as I have discovered the root tag is taken as the last tag at the first tab indent not the opening tag.

here is an example:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Orders xmlns="http://www.spscommerce.com/RSX">
<Order>
    <Meta>
        ....
    </Meta>
    <Header>
        ....
    </Header>
    ....
</Order>
</Orders>
```

results with array of: 

```
'Meta' => 
  array (
   ....
  ),
 'Header' => 
  array (
   ....
  )
```

As you can see it completely ignores the '<Order>' tag.

However if you indent the Order tag it includes it.

A fix for this would be appreciated

Thanks
