### ISSUE TITLE
is this bug?

### ISSUE THREAD

**Issue by dyike** [nathanmac/Parser#45]
here is a example:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<webcast id="f35e1dc">
    <question id="715da0d" time="1400470679" uid="9934592202" uname="admin">qustion
        <answer id="0e9a009" time="1400470699" uid="1" uname="admin">answer</answer>
    </question>  
</webcast>
```
use the function `xml`, then get the following result: [the 'question' is missing]
```
Array
(
    [@id] => f35e1dc
    [question] => Array
        (
            [@id] => 715da0d
            [@time] => 1400470679
            [@uid] => 9934592202
            [@uname] => admin
            [answer] => Array
                (
                    [#text] => answer
                    [@id] => 0e9a009
                    [@time] => 1400470699
                    [@uid] => 1
                    [@uname] => admin
                )
        )
)
```

**Comment by Tommixoft** [comment]
creator doesnt give a damn

**Comment by danhunsaker** [comment]
@Tommixoft - That's quite an accusation. I can see that you're very upset about something, but all you're doing about it is complaining about the documentation (which, yes, could be improved) and accusing someone you've never met of apathy, as though they owe you or anyone else here their time. To my knowledge, this is an open source project created on the side, not a product anyone is paying to use or maintain. That means the project's creator has to have work elsewhere to pay bills and basically survive, which doesn't often leave much time to review side projects, especially older ones. You may well be justified in being upset. But don't expect anyone else to understand it, or to instantly jump to make you feel better.

That said.

@dyike - I'm not certain why the `#text` entry isn't being set, here. I'm not sure how many XML parsers allow mixing text and tag contents (SGML does, and both HTML and XML are based on it, but XML is more restrictive, so many parsers skip supporting mixed content). This might be a bug, yes. I'd have to look at the code to see what's going on there.

You'll have the most success with the most XML libraries if you avoid mixing text and tags. That's not an answer to your question, but it is a general guideline to follow if you want to interact with other projects.
