### ISSUE TITLE
Is there any problem with multidimensional xml to array conversion?

### ISSUE THREAD

**Issue by arturcesarmelo** [nathanmac/Parser#48]
This is the xml that i receive

![captura de tela 2017-08-09 as 15 44 34](https://user-images.githubusercontent.com/18191910/29138348-d364c730-7d19-11e7-8215-415076702091.png)

here is the array parsed

![captura de tela 2017-08-09 as 15 44 49](https://user-images.githubusercontent.com/18191910/29138387-ea06a29c-7d19-11e7-91bb-7c0998822015.png)

inside *bets* tags, has many *bet* with many *choices* tags. But array parsed gives me back something pretty wrong.

Is there something i'm doing wrong?

**Comment by danhunsaker** [comment]
Everything that I can see, here, looks right. You mention the contents of `<bets>` being wrong, but don't actually show it in the images, here, so I have no idea what's wrong about them.

What are you expecting to get back?

**Comment by arturcesarmelo** [comment]
i'm i new bye and i spend your time for nothing. Sorry. the **@** before attribute name is called by method. so, all that i have to do is $variable->name(); $variable->start_date();... etc. 

I'm sorry, brow.
