### ISSUE TITLE
ParserException in JSON.php line 30: Failed To Parse JSON

### ISSUE THREAD

**Issue by signinsatish** [nathanmac/Parser#49]
hi,

we are using nathanmac and first time getting this kind of error and it is showing error in parser.php. tell me the reason for this.

thanks in advance.

**Comment by signinsatish** [comment]
and i am getting message like

 JSON->parse('<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Temporarily Unavailable</title> </head><body> <h1>Service Temporarily Unavailable</h1> <p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.</p> <p>Additionally, a 503 Service Temporarily Unavailable error was encountered while trying to use an ErrorDocument to handle the request.</p>

**Comment by signinsatish** [comment]
hi,

issue has been resolved, another internal server has been not working initially, now it is working fine

**Comment by danhunsaker** [comment]
Can't parse HTML as JSON, no. 😄

If your issue is resolved, you might consider closing the issue.
